#pragma config(Motor,  port2,           A,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           B,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           C,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           d1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           d2,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define _A(SPEED) motor[A]=SPEED;
#define A_(SPEED) motor[A]=-SPEED;
#define _B(SPEED) motor[B]=-SPEED;
#define B_(SPEED) motor[B]=SPEED;
#define _C(SPEED) motor[C]=-SPEED;
#define C_(SPEED) motor[C]=SPEED;

#define MAX 100;

//movimientos
void front(int vel){
	_A(vel);
	_B(vel);
	C_(0);
}
void back(int vel){
	A_(vel);
	B_(vel);
	C_(0);
}
void left(int vel){
	A_(0);
	B_(vel);
	_C(vel);
}
void right(int vel){
	C_(vel);
	A_(vel);
	B_(0);
}
void off(){
	A_(0);
	B_(0);
	_C(0);
}
void turnright(int vel){
	A_(vel);
	_B(vel);
	_C(vel);
}
void turnleft(int vel){
	_A(vel);
	B_(vel);
	C_(vel);
}

//control
int velocidad(){
	if(vexRT[Btn6D]){
		return MAX;
	}
	else if(vexRT[Btn5D]){
		return 30;
	}
	else {
		return 60;
	}
}
void movimientos(int vel){
	if(vexRT[Btn7U]){
		front(vel);
	}
	else if(vexRT[Btn7D]){
		back(vel);
	}
	else if(vexRT[Btn7R]){
		right(vel);
	}
	else if(vexRT[Btn7L]){
		left(vel);
	}
	else {
		off();
	}
}
void giros(int vel){
	if(vexRT[Btn6U]){
		turnright(vel);
	}
	else if(vexRT[Btn5U]){
		turnleft(vel);
	}
	else {
		off();
	}
}
task main()
{
	int vel=50;
	bool suc=true;
	while(true){
		vel=velocidad();
	 	if(vexRT[Btn5U] || vexRT[Btn6U]){
	 		giros(vel);
	 	}
	 	else {
	 		movimientos(vel);
	 	}
	 	if(vexRT[Btn8U]){
	 		motor[d1]=-50;
	 		motor[d2]=-50;
	 	}
	 	else if(vexRT[Btn8D]){
	 		motor[d1]=50;
	 	}
	 	else if(vexRT[Btn8L]){
	 		motor[d1]=0;
	 	}
		if(vexRT[Btn8R]){
			motor[d2]=100;
		}
		else {
			motor[d2]=0;
		}
	}
}
